name: CI/CD for Open WebUI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Install dependencies from the requirements file

    - name: Run tests
      run: |
        echo "Running tests..."
        pytest tests/  # Adjust if tests are located elsewhere

    - name: Deploy
      run: |
        echo "Deploying application..."
        # Add deployment logic here, e.g., copy files to the appropriate server or location
        # If using WSL, you might add specific WSL commands to start services locally
