name: CI/CD for Open WebUI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Check if requirements.txt is in a subdirectory
        pip install -r open-webui/backend/requirements.txt  # Adjust the path if necessary

    - name: Run tests
      run: |
        echo "Running tests..."
        pytest tests/  # Adjust if tests are located elsewhere

    - name: Deploy
      run: |
        echo "Deploying application..."
        # Add deployment logic here
